swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger ReST Article
consumes:
  - application/json
produces:
  - application/json


# Paths supported by the server application
paths:
  /datasets:
    get:
      operationId: get_dataset_by_id
      tags:
        - Datasets
      summary: Retrieve a Dataset by its ID
      description: This retrieves an existing *Dataset*. The API user indicates a *Dataset ID*. The GET request returns a *Dataset object*.
      x-swagger-router-controller: controllers.datasets_controller
      parameters:
        - name: requested_dataset_id
          in: query
          type: string
          description: The API user indicates a Dataset ID
          required: true
      responses:
        200:
          description: Successfully read people list operation
          schema:
            type: object
            properties:
              dataset_id:
                type: string
                example: '40655045bfy'
              dataset_filename:
                type: string
                example: 'KPIs Sheet.xlsx'
              dataset_rows:
                type: integer
                example: 1500
              dataset_columns:
                type: integer
                example: 8
              dataset_headers:
                type: array
                items:
                  type: string
                  example: ['Revenue','Sign-Ups','Active Users']
    post:
      operationId: post_dataset_with_file
      x-swagger-router-controller: controllers.datasets_controller
      tags:
        - Datasets
      summary: Creates a new Dataset
      description: This processes data provided by the API user and creates a new *Dataset*. The API user uploads a data *Source file*. The POST request returns a *Dataset ID*.
      consumes:
        - multipart/form-data
      parameters:
          - in: formData
            name: source_file
            type: file
            required: true
            description: The file to upload.
      responses:
        201:
          description: Succesful *Dataset* creation
          schema:
            type: object
            properties:
              dataset_id:
                type: string
                example: '40655045bfy'